# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Pynapple Codes
tagline:	'Python tutorials'
description:	'Learn Python with my awesome Python tutorials!'
url:		# leave this blank so it works on any URL

author:
  name:		'PixelFireblade'
  url:		https://pixelfireblade.github.io/

paginate:	7

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  #- icon:	twitter
  #  url:	https://twitter.com/iancamporez
  #  desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/PixelFireblade
    desc:	Follow me on github

  #- icon:	googleplus-alt
  #  url:	https://google.com/+IanCamporezBrunelli
  #  desc:	Add me on google+

  - icon:	feed
    url:	/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
copyright:
  author:	PixelFireblade
  url:		https://pixelfireblade.github.io/
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
